Class
	https://leetcode.com/problems/two-sum/
	https://leetcode.com/problems/first-unique-character-in-a-string/
	https://leetcode.com/problems/valid-anagram/
	https://leetcode.com/problems/intersection-of-two-arrays/
	https://leetcode.com/problems/find-all-anagrams-in-a-string/
	https://leetcode.com/problems/permutation-in-string/
	https://leetcode.com/problems/maximum-size-subarray-sum-equals-k/
	https://leetcode.com/problems/subarray-sum-equals-k/
	https://leetcode.com/problems/contiguous-array/
	https://leetcode.com/problems/longest-consecutive-sequence/
	https://www.geeksforgeeks.org/count-of-substrings-having-all-distinct-characters/
	https://leetcode.com/problems/longest-substring-without-repeating-characters/
	https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/
	https://leetcode.com/problems/max-consecutive-ones/
	https://leetcode.com/problems/max-consecutive-ones-ii/

Homework
	https://www.geeksforgeeks.org/count-pairs-with-given-sum/
	https://leetcode.com/problems/intersection-of-two-arrays-ii/
	https://leetcode.com/problems/group-anagrams/
	https://leetcode.com/problems/subarray-sums-divisible-by-k/
	https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/
	https://leetcode.com/problems/max-consecutive-ones-iii/
	https://leetcode.com/problems/degree-of-an-array/
	https://www.geeksforgeeks.org/count-subarrays-equal-number-1s-0s/
	https://leetcode.com/problems/4sum-ii/
	https://leetcode.com/problems/max-points-on-a-line/